Adressboken/Controllers/KundController.cs
using Microsoft.AspNetCore.Mvc;
using MongoDB.Driver;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity.UI.Services;
using Microsoft.Extensions.Configuration;

namespace Adressboken.Controllers
{
    [Authorize]
    public class KundController : Controller
    {
        private readonly IMongoCollection<Kund> _addressCollection;
        private readonly IEmailSender emailSender;
        
        public KundController(IMongoDatabase database, IEmailSender emailSender)
        {
            _addressCollection = database.GetCollection<Kund>("addresses");
            this.emailSender = emailSender;
        }

        //Lagt till Authentisering
        public async Task<IActionResult> Index()
        {
            var addresses = await _addressCollection.Find(_ => true).ToListAsync();
            return View(addresses);
        }

        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Create(Kund address)
        {

        if (ModelState.IsValid)
            {
                await _addressCollection.InsertOneAsync(address);
                return RedirectToAction("Index");
            }
        return View(address); // Visa vyn med felaktig modell om validering misslyckas

        }

        public async Task<IActionResult> Edit(string id)
        {
            var address = await _addressCollection.Find(a => a.Id == id).FirstOrDefaultAsync();
            if (address == null)
            {
                return NotFound();
            }
            return View(address);
        }

        [HttpPost]
        public async Task<IActionResult> Edit(string id, Kund updatedAddress)
        {
            await _addressCollection.ReplaceOneAsync(a => a.Id == id, updatedAddress);
            return RedirectToAction("Index");
        }

        public async Task<IActionResult> Delete(string id)
        {
            var address = await _addressCollection.Find(a => a.Id == id).FirstOrDefaultAsync();
            if (address == null)
            {
                return NotFound();
            }
            return View(address);
        }

        [HttpPost]
        public async Task<IActionResult> DeleteConfirmed(string id)
        {
            await _addressCollection.DeleteOneAsync(a => a.Id == id);
            return RedirectToAction("Index");
        }

        [HttpGet]
        public async Task<IActionResult> Search(string query)
        {
            if (query == null)
            {
                // Handle the case where query is null, such as showing all results
                var allResults = await _addressCollection.Find(_ => true).ToListAsync();
                return PartialView("_SearchResults", allResults);
            }

            var searchResults = await _addressCollection.Find(a =>
                (a.Namn != null && a.Namn.Contains(query)) ||
                (a.Adress != null && a.Adress.Contains(query)) ||
                (a.Telefonnummer != null && a.Telefonnummer.Contains(query)) ||
                (a.Email != null && a.Email.Contains(query)) ||
                (a.Bilmodell != null && a.Bilmodell.Contains(query)) ||
                (a.Årsmodell != null && a.Årsmodell.Contains(query))).ToListAsync();

            return PartialView("_SearchResults", searchResults);
        }

        public async Task<IActionResult> ReparationKlar(string id)
        {
            var address = await _addressCollection.Find(a => a.Id == id).FirstOrDefaultAsync();
            if (address == null)
            {
                return NotFound();
            }

            if (!address.ReparationKlar)
            {
                address.ReparationKlar = true;

                // Uppdatera dokumentet med den nya statusen
                await _addressCollection.ReplaceOneAsync(a => a.Id == id, address);

                // Skicka e-post till kunden
                if (!string.IsNullOrEmpty(address.Email) && address.ReparationKlar)
                {
                    string subject = "Reparationen är klar";
                    string message = "Din reparation är klar. Vänligen kontakta oss för att hämta din bil.";

                    try
                    {
                        // Skicka e-post till kunden med din EmailSender
                        await emailSender.SendEmailAsync(address.Email, subject, message);
                    }
                    catch (Exception ex)
                    {
                        Console.WriteLine("Gick ej att maila!");
                        // Logga felet eller visa felmeddelande på klienten
                    }
                }
            }

            return RedirectToAction("Index");
        }

    }
}

Adressboken/Controllers/VehicleController.cs
using Adressboken.Models;
using Adressboken.Services;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace Adressboken.Controllers
{
    [Authorize]
    public class VehicleController : Controller
    {
        private readonly RegCheckApiService _regCheckApiService;

        public VehicleController(RegCheckApiService regCheckApiService)
        {
            _regCheckApiService = regCheckApiService;
        }

        public IActionResult Index()
        {
            return View();
        }


        [HttpPost]
        public async Task<IActionResult> Search(VehicleSearchViewModel viewModel)
        {
            if (!string.IsNullOrEmpty(viewModel.Regnummer))
            {
                string registrationNumber = viewModel.Regnummer;

                // Anropa RegCheckApiService för att söka efter fordonets uppgifter
                var vehicleDetails = await _regCheckApiService.GetVehicleDetailsAsync(registrationNumber);

                viewModel.VehicleDetails = vehicleDetails;

                if (vehicleDetails == null)
                {
                    ViewBag.ErrorMessage = "No vehicle details found.";
                }
            }
            else
            {
                viewModel.VehicleDetails = null;
            }

            return View("Index", viewModel);
        }






    }
}

Adressboken/Views/Vehicle/Index.cshtml
@model Adressboken.Models.VehicleSearchViewModel

<h2>Sök på regnr.</h2>

<div class="d-flex justify-content-between">
    @using (Html.BeginForm("Search", "Vehicle", FormMethod.Post, new { @class = "form-inline" }))
    {
        <div class="input-group">
            
            @Html.TextBoxFor(m => m.Regnummer, new { @class = "form-control", @placeholder = "Sök efter fordon..." })
            <div class="input-group-append">
                <button type="submit" class="btn btn-primary">Sök</button>
            </div>
        </div>
    }
</div>

@if (Model?.VehicleDetails != null)
{
    <div class="row">
        <div class="col-md-8">
            <h2>Bildata:</h2>
            <strong>Märke och modell:</strong> @Model.VehicleDetails?.CarMake?.CurrentTextValue @Model.VehicleDetails?.CarModel?.CurrentTextValue
            <br />
            <strong>Årsmodell:</strong> @Model.VehicleDetails?.RegistrationYear
            <br />
            <strong>Motorstorlek:</strong> @Model.VehicleDetails?.EngineSize?.CurrentTextValue
            <br />
            <strong>Bränsle:</strong> @Model.VehicleDetails?.FuelType?.CurrentTextValue
            <br />
            <strong>Kaross:</strong> @Model.VehicleDetails?.BodyStyle?.CurrentTextValue
            <br />
            <strong>Färg:</strong> @Model.VehicleDetails?.Colour
            <br />
            <strong>I bruk:</strong> @Model.VehicleDetails?.RegistrationDate
            <br />
            <strong>Märke:</strong> @Model.VehicleDetails?.MakeDescription?.CurrentTextValue
            <br />
            <strong>Modell:</strong> @Model.VehicleDetails?.ModelDescription?.CurrentTextValue
            <br />
            <strong>Antal säten:</strong> @Model.VehicleDetails?.NumberOfSeats?.CurrentTextValue
            <br />
            <strong>VIN:</strong> @Model.VehicleDetails?.VechileIdentificationNumber
            <br />
        </div>
        <div class="col-md-4 text-center">
            <img src="@Model.VehicleDetails?.ImageUrl" alt="Vehicle Image" class="img-fluid rounded" />
        </div>
    </div>

    <div class="text-center mt-3">
        <a href="@Url.Action("Index", "Kund")" class="btn btn-secondary">Tillbaka till Kundregister</a>
    </div>


}